repos:
- hooks:
  - args:
    - --in-place
    - --make-summary-multi-line
    - --close-quotes-on-newline
    - --wrap-summaries
    - '88'
    entry: docformatter
    files: \.py
    id: docformatter
    language: system
    name: docformatter
    pass_filenames: true
  - args:
    - check
    - --fix
    - .
    entry: ruff
    id: ruff
    language: system
    name: ruff
    pass_filenames: false
  - args:
    - format
    - .
    entry: ruff
    id: ruff-format
    language: system
    name: ruff-format
    pass_filenames: false
  - args:
    - -m
    - libcst.tool
    - codemod
    - autotyping.AutotypeCommand
    - --aggressive
    entry: python
    files: \.py
    id: infer-missing-annotations
    language: system
    name: infer-missing-annotations
    pass_filenames: true
  - args:
    - .
    entry: mypy
    fail_fast: true
    id: mypy
    language: system
    name: mypy
    pass_filenames: false
    require_serial: true
  - entry: coverage run
    fail_fast: true
    id: run-tests
    language: system
    name: run-tests
    pass_filenames: false
  - entry: check-coverage
    id: check-coverage
    language: system
    name: check-coverage
    pass_filenames: false
  - entry: check-shields
    id: check-shields
    language: system
    name: check-shields
    pass_filenames: false
  - entry: check-version
    id: check-version
    language: system
    name: check-version
    pass_filenames: false
  - entry: check-import
    id: check-import
    language: system
    name: check-import
    pass_filenames: false
  repo: local
